const fruits = [
    {
      genus: 'Malus',
      name: 'Apple',
      id: 6,
      family: 'Rosaceae',
      url: 'https://rb.gy/4dfe5k',
      order: 'Rosales',
      nutritions: {
        carbohydrates: 11.4,
        protein: 0.3,
        fat: 0.4,
        calories: 52,
        sugar: 10.3,
        price:10,
      },
    },
    {
      genus: 'Prunus',
      name: 'Apricot',
      id: 35,
      family: 'Rosaceae',
      url: 'https://rb.gy/pllxc2',
      order: 'Rosales',
      nutritions: {
        carbohydrates: 3.9,
        protein: 0.5,
        fat: 0.1,
        calories: 15,
        sugar: 3.2,
        price:9,
      },
    },
    {
      genus: 'Musa',
      name: 'Banana',
      id: 1,
      family: 'Musaceae',
      url: 'https://rb.gy/r8wpfu',
      order: 'Zingiberales',
      nutritions: {
        carbohydrates: 22,
        protein: 1,
        fat: 0.2,
        calories: 96,
        sugar: 17.2,
        price:11,
      },
    },
    {
      genus: 'Fragaria',
      name: 'Blueberry',
      id: 33,
      family: 'Rosaceae',
      url: 'https://rb.gy/zidgih',
      order: 'Rosales',
      nutritions: {
        carbohydrates: 5.5,
        protein: 0,
        fat: 0.4,
        calories: 29,
        sugar: 5.4,
        price:20,
      },
    },
    {
      genus: 'Prunus',
      name: 'Cherry',
      id: 9,
      family: 'Rosaceae',
      url: 'https://rb.gy/ynlarw',
      order: 'None',
      nutritions: {
        carbohydrates: 12,
        protein: 1,
        fat: 0.3,
        calories: 50,
        sugar: 8,
        price:7,
      },
    },
    {
      genus: 'Durio',
      name: 'Durian',
      id: 60,
      family: 'Malvaceae',
      url: 'https://rb.gy/4ynlrm',
      order: 'Malvales',
      nutritions: {
        carbohydrates: 27.1,
        protein: 1.5,
        fat: 5.3,
        calories: 147,
        sugar: 6.75,
        price:10,
      },
    },
    {
      genus: 'Vitis',
      name: 'Grapes',
      id: 47,
      family: 'Vitaceae',
      url: 'https://rb.gy/rsbeqp',
      order: 'Vitales',
      nutritions: {
        carbohydrates: 18.1,
        protein: 0.72,
        fat: 0.16,
        calories: 69,
        sugar: 15.48,
        price:15,
      },
    },
    {
      genus: 'Psidium',
      name: 'Guava',
      id: 37,
      family: 'Myrtaceae',
      url: 'https://rb.gy/c30pgr',
      order: 'Myrtales',
      nutritions: {
        carbohydrates: 14,
        protein: 2.6,
        fat: 1,
        calories: 68,
        sugar: 9,
        price:19,
      },
    },
    {
      genus: 'Citrus',
      name: 'Lemon',
      id: 26,
      family: 'Rutaceae',
      url: 'https://rb.gy/ijr1ku',
      order: 'Sapindales',
      nutritions: {
        carbohydrates: 9,
        protein: 1.1,
        fat: 0.3,
        calories: 29,
        sugar: 2.5,
        price:5,
      },
    },
    {
      genus: 'Citrus',
      name: 'Lime',
      id: 44,
      family: 'Rutaceae',
      url: 'https://rb.gy/lz2btg',
      order: 'Sapindales',
      nutritions: {
        carbohydrates: 8.4,
        protein: 0.3,
        fat: 0.1,
        calories: 25,
        sugar: 1.7,
        price:22,
      },
    },
    {
      genus: 'Mangifera',
      name: 'Mango',
      id: 27,
      family: 'Anacardiaceae',
      url: 'https://rb.gy/7nxltq',
      order: 'Sapindales',
      nutritions: {
        carbohydrates: 15,
        protein: 0.82,
        fat: 0.38,
        calories: 60,
        sugar: 13.7,
        price:9,
        
      },
    },
    {
      genus: 'Cucumis',
      name: 'Melon',
      id: 41,
      family: 'Cucurbitaceae',
      order: 'Cucurbitaceae',
      nutritions: {
        carbohydrates: 8,
        protein: 0,
        fat: 0,
        calories: 34,
        price:10,
        sugar: 8,
        url:"https://i.pinimg.com/236x/1e/d9/3f/1ed93f6693ef0c2744a43b79a40c9200.jpg",
      },
    },
    {
      genus: 'Citrus',
      name: 'Orange',
      id: 2,
      family: 'Rutaceae',
      order: 'Sapindales',
      nutritions: {
        carbohydrates: 8.3,
        protein: 1,
        fat: 0.2,
        calories: 43,
        sugar: 8.2,
        price:16,
        url:"https://i.pinimg.com/236x/05/79/5a/05795a16b647118ffb6629390e995adb.jpg",
      },
    },
    {
      genus: 'Carica',
      name: 'Papaya',
      id: 42,
      family: 'Caricaceae',
      order: 'Caricacea',
      nutritions: {
        carbohydrates: 11,
        protein: 0,
        fat: 0.4,
        calories: 43,
        sugar: 1,
        price:7,
        url :"https://i.pinimg.com/236x/2e/77/9b/2e779b566ebd69426f552ceb8e66b7de.jpg",
      },
    },
  ];

  export default fruits;